services:
  - type: web
    name: api1
    env: python
    buildCommand: "pip install -r requirements.txt && playwright install --with-deps chromium"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
